# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rico.Asset')),
            ],
        ),
    ]
