# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 12:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rico', '0003_auto_20170721_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('resolution', models.CharField(choices=[('NO', 'None'), ('MA', 'Manual'), ('GF', 'Ground FDIR'), ('SF', 'Space FDIR'), ('SO', 'Solved'), ('CR', 'Cannot Reproduce'), ('CF', 'Cannot Fix'), ('OB', 'OBE')], default='NO', max_length=2)),
                ('comments', models.ManyToManyField(to='rico.Comment')),
                ('faults', models.ManyToManyField(to='rico.Fault')),
            ],
        ),
        migrations.AddField(
            model_name='fault',
            name='comments',
            field=models.ManyToManyField(to='rico.Comment'),
        ),
    ]
