# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rico', '0004_auto_20170724_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fault',
            old_name='body',
            new_name='message',
        ),
    ]
