# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rico', '0005_auto_20170725_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fault',
            old_name='message',
            new_name='description',
        ),
        migrations.AddField(
            model_name='fault',
            name='title',
            field=models.CharField(default='defaulttitle', max_length=140),
            preserve_default=False,
        ),
    ]
