# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rico', '0006_auto_20170725_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fault',
            name='asset',
        ),
        migrations.AddField(
            model_name='asset',
            name='faults',
            field=models.ManyToManyField(to='rico.Fault'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='fault',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fault',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
